version: "2.4"

services:
  christmoji:
    restart: unless-stopped
    build: .
    pids_limit: 256
    mem_limit: 64M
    cpus: 0.5
    volumes:
      - ./data:/app/data
    ports:
      - 1337:1337

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - "./data:/data"
    environment:
      - DELETE_AFTER=15m
      - SLEEP=5m
      - DIRS=/data
